image:
  name: harbor-repo.vmware.com/nexus/runner:latest

include:
- project: "nsx-allspark_users/nexus-sdk/integration-tests"
  file: ".gitlab-ci-template.yml"

variables:
  REPOSITORY: nsx-allspark_users/nexus-sdk/compiler

before_script:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
  - git config --global gc.auto 0
  - git config --global credential.helper store

.create_builder: &create_builder
  - export CONTAINER_ID=$(docker ps -q -f "label=com.gitlab.gitlab-runner.job.id=$CI_JOB_ID" -f "label=com.gitlab.gitlab-runner.type=build")
  - USE_SSH=false make docker.builder

.setup_aws: &setup_aws
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  -  docker login --username AWS -p $(aws ecr get-login-password --region us-west-2) 284299419820.dkr.ecr.us-west-2.amazonaws.com

.harbor_login: &harbor_login
  - docker login harbor-repo.vmware.com --username $DOCKER_USERNAME --password $DOCKER_PASSWORD

test:
  stage: test
  only:
    - merge_requests
    - master
  script:
    - *setup_aws
    - *create_builder
    - CONTAINER_ID=$CONTAINER_ID PKG_NAME=/builds/${REPOSITORY} make test_in_container
    - CONTAINER_ID=$CONTAINER_ID PKG_NAME=/builds/${REPOSITORY} make test_render_templates
    - CONTAINER_ID=$CONTAINER_ID PKG_NAME=/builds/${REPOSITORY} make test_generate_code_in_container

build:
  stage: build
  only:
    - merge_requests
    - master
  script:
    - *setup_aws
    - *create_builder
    - *harbor_login
    - PKG_NAME=/builds/${REPOSITORY} make docker TAG=$CI_COMMIT_SHA
    - make publish TAG=$CI_COMMIT_SHA

publish:
  stage: build
  only:
    - tags
  script:
    - *setup_aws
    - *create_builder
    - *harbor_login
    - PKG_NAME=/builds/${REPOSITORY} make docker TAG=$CI_COMMIT_TAG
    - make publish TAG=$CI_COMMIT_TAG

coverage:
  before_script:
    - git config --global url."https://gitlab.eng.vmware.com/".insteadOf "git@gitlab.eng.vmware.com:"
    - git config --global gc.auto 0
    - git config --global credential.helper store
    - export GOPRIVATE=*.eng.vmware.com
    - echo -e  "https://gitlab-ci-token:${CICD_TOKEN}@gitlab.eng.vmware.com/" >> ~/.git-credentials
  image: runner.servicemesh.biz:5000/allspark/runner:latest
  stage: coverage
  variables:
    GIT_DEPTH: 0
  only:
    - merge_requests
    - master
  script:
    - make coverage
    - sonar-scanner

integration_test:
  stage: integration_test
  only:
    - merge_requests
    - master
  variables:
    NEXUS_DATAMODEL_COMPILER_VERSION: $CI_COMMIT_SHA
  extends: .run_integration_test

stages:
  - test
  - build
  - coverage
  - integration_test
