---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: foowrappers.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Foowrapper
    listKind: FoowrapperList
    plural: foowrappers
    shortNames:
    - foowrapper
    singular: foowrapper
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          foo:
            properties:
              doubleValue:
                format: double
                type: number
              floatValue:
                format: float
                type: number
              int32Value:
                format: int32
                type: integer
              int64Value:
                format: int64
                type: integer
              uint32Value:
                format: int64
                type: integer
              uint64Value:
                format: int64
                type: integer
              sint32Value:
                format: int32
                type: integer
              sint64Value:
                format: int64
                type: integer
              fixed32Value:
                format: int64
                type: integer
              fixed64Value:
                format: int64
                type: integer
              sfixed32Value:
                format: int32
                type: integer
              sfixed64Value:
                format: int64
                type: integer
              boolValue:
                type: boolean
              stringValue:
                type: string
              bytesValue:
                format: byte
                type: string
              enumValue:
                type: string
              nestedEnumValue:
                type: string
              nestedMessage:
                properties:
                  nestedMessageValue:
                    type: string
                type: object
              oneofValueInt:
                format: int32
                type: integer
              oneofValueString:
                type: string
              mapValue:
                additionalProperties:
                  default: ""
                  type: string
                type: object
              repeatedValue:
                items:
                  default: 0
                  format: int32
                  type: integer
                type: array
              barValue:
                properties:
                  enumValue:
                    type: string
                  oneofValueInt:
                    format: int32
                    type: integer
                  oneofValueString:
                    type: string
                type: object
            type: object
          metadata:
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
