---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: foos.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Foo
    listKind: FooList
    plural: foos
    shortNames:
    - foo
    singular: foo
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          buzz:
            type: integer
          fizz:
            type: string
          metadata:
            type: object
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: fizzs.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Fizz
    listKind: FizzList
    plural: fizzs
    shortNames:
    - fizz
    singular: fizz
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          baz:
            type: string
          bazBar:
            type: string
          metadata:
            type: object
        required:
        - baz
        - bazBar
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1

