---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: bars.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Bar
    listKind: BarList
    plural: bars
    shortNames:
    - bar
    singular: bar
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          metadata:
            type: object
          foo:
            type: string
        type: object
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
  - v1

