apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    nexus: |
      {"name":"bizz","is_singleton":false,"nexus-rest-api-gen":{"uris":null}}
  creationTimestamp: null
  name: bizzs.test.it
spec:
  conversion:
    strategy: None
  group: test.it
  names:
    kind: Bizz
    listKind: BizzList
    plural: bizzs
    shortNames:
      - bizz
    singular: bizz
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            baz:
              type: string
            bazBar:
              type: string
            metadata:
              type: object
          required:
            - baz
            - bazBar
          type: object
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions:
    - v1
