name: Release compiler image and CLI Binaries
on:
  create:
    tags:
      - v*
jobs:
  release-compiler-image:
    name: Release compiler image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: setup-docker
        uses: docker-practice/actions-setup-docker@1.0.11
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'
      - name: Build Compiler image
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GCPServiceAccountKey }}
          GCR_REPOSITORY: gcr.io/nsx-sm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            set -x
            echo $GOOGLE_SERVICE_ACCOUNT_KEY | docker login -u _json_key --password-stdin $GCR_REPOSITORY
            git config --global url."https://github.com/".insteadOf "git@github.com:"
            IMAGE_TAG=$GITHUB_REF_NAME
            echo "Building compiler image with tag: $IMAGE_TAG"
            pushd compiler
              make docker.builder
              make build_in_container
              make docker TAG=$IMAGE_TAG
              make publish TAG=$IMAGE_TAG
            popd
            pushd cli
              make build BUILD_VERSION=$GITHUB_REF_NAME
            popd
      - name: Upload CLI Binaries - DarwinAMD64
        id: upload-cli-binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/vmware-tanzu/graph-framework-for-microservices/releases/$GITHUB_REF_NAME/assets
          asset_path: ./cli/artifcats/nexus/nexus-darwin_amd64
          asset_name: nexus-darwin_amd64
          asset_content_type: application/octet-stream
      - name: Upload CLI Binaries - LinuxAMD64
        id: upload-cli-binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
        with:
          upload_url: https://uploads.github.com/repos/vmware-tanzu/graph-framework-for-microservices/releases/$GITHUB_REF_NAME/assets
          asset_path: ./cli/artifcats/nexus/nexus-linux_amd64
          asset_name: nexus-linux_amd64
          asset_content_type: application/octet-stream
      - name: Upload CLI Binaries - LinuxARM64
        id: upload-cli-binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/vmware-tanzu/graph-framework-for-microservices/releases/$GITHUB_REF_NAME/assets
          asset_path: ./cli/artifcats/nexus/nexus-linux_arm64
          asset_name: nexus-linux_arm64
          asset_content_type: application/octet-stream
      - name: Upload CLI Binaries - DarwinARM64
        id: upload-cli-binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/vmware-tanzu/graph-framework-for-microservices/releases/$GITHUB_REF_NAME/assets
          asset_path: ./cli/artifcats/nexus/nexus-darwin_arm64
          asset_name: nexus-darwin_arm64
          asset_content_type: application/octet-stream
